AWSTemplateFormatVersion: '2010-09-09'
Description: Shared services NAT instance stack

Parameters:
  PrivateSubnetCidr:
    Type: String
    Description: CIDR block of the private subnet
    Default: 10.0.2.64/27

Resources:
  NatInstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow all traffic to NAT instance from private subnet
      VpcId: !ImportValue management-stack-VpcId
      SecurityGroupIngress:
        - IpProtocol: -1
          CidrIp: !Ref PrivateSubnetCidr
          Description: Allow all inbound traffic from private subnet
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic to anywhere
      Tags:
        - Key: Name
          Value: "management-nat-instance-sg"

  # NAT instance using Amazon Linux 2023 AMI

  NatInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-011d5239d6804e25e
      InstanceType: t3.micro
      KeyName: bear
      NetworkInterfaces:
      - AssociatePublicIpAddress: true
        DeviceIndex: 0
        GroupSet: 
          - !Ref NatInstanceSecurityGroup
        SubnetId: !ImportValue management-stack-PublicSubnetAId
      BlockDeviceMappings:
        - DeviceName: "/dev/xvda"
          Ebs:
            VolumeType: gp3
            DeleteOnTermination: true
            VolumeSize: 10
      SourceDestCheck: false
      IamInstanceProfile: ssm-quick-setup
      Tags:
        - Key: Name
          Value: "management-nat-instance"

