AWSTemplateFormatVersion: "2010-09-09"
Description: Production OCP management server stack

# Unlike SSM Session Manager, EC2 Instance Connect requires port
# tcp/22 to be open on the instance's security group.

# RHEL-9.8.0_HVM-20260908-x86_64-0-Hourly2-GP3

Parameters:
  AmiId:
    Type: AWS::EC2::Image::Id
    Description: "ID of AMI to use for OCP Management server instance"
    Default: ami-0b77fd0a4e70d9ca6

Resources:

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Development EKS Manager security group
      VpcId: !ImportValue prod-network-stack-VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          SourceSecurityGroupId: !ImportValue prod-network-stack-ManagementInstanceConnectEndpointSecurityGroupId
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic to anywhere
      Tags:
        - Key: Name
          Value: "prod-ocp-management-server-sg"

  # We should use RHEL 9.8 AMI. Normally, do not associate a public IP
  # in CFn. Instead, do it manually whenever required to avoid costs
  # associated with a public IP. However, it might be needed in order
  # to download things when user data script is being run.

  # Note: SSM quick setup is probably not required since we are using
  # EC2 Instance Connect instead of SSM Session Manager.

  # Note: Key pair is omitted because we are using EC2 Instance
  # Connect instead of traditional SSH logins.

  # Use public IP so it can download RPM packages.

  # TODO: Set IDMSv2

  Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref AmiId
      InstanceType: t3.small
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          GroupSet:
            - !Ref SecurityGroup
          SubnetId: !ImportValue prod-network-stack-ManagementSubnetId
      BlockDeviceMappings:
        - DeviceName: "/dev/sda1"
          Ebs:
            VolumeType: gp3
            DeleteOnTermination: true
            VolumeSize: 60
      IamInstanceProfile: !ImportValue prod-ocp-management-iam-stack-InstanceProfileName
      MetadataOptions:
        HttpEndpoint: enabled
        HttpPutResponseHopLimit: 1
        HttpTokens: required
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          # Install EC2 Instance Connect packages
          HOST="amazon-ec2-instance-connect-us-west-2.s3.us-west-2.amazonaws.com"
          PACKAGE1="ec2-instance-connect-2.0.0-5.rhel9.x86_64.rpm"
          PACKAGE2="ec2-instance-connect-selinux-2.0.0-5.noarch.rpm"
          mkdir /tmp/ec2-instance-connect
          curl https://${!HOST}/latest/linux_amd64/${!PACKAGE1} -o /tmp/ec2-instance-connect/ec2-instance-connect.rpm
          curl https://${!HOST}/latest/linux_amd64/${!PACKAGE2} -o /tmp/ec2-instance-connect/ec2-instance-connect-selinux.rpm
          dnf install -y /tmp/ec2-instance-connect/ec2-instance-connect.rpm
          dnf install -y /tmp/ec2-instance-connect/ec2-instance-connect-selinux.rpm
          # Install AWS CLI
          #curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          #dnf install -y unzip
          #unzip awscliv2.zip
          #sudo ./aws/install
      Tags:
        - Key: Name
          Value: "prod-ocp-management-server-instance"



  # ForwardRecord:
  #   Type: AWS::Route53::RecordSet
  #   Properties:
  #     HostedZoneId: !ImportValue dns-stack-ForwardZoneId
  #     Name: "eks-manager.dev.saber.net"
  #     Type: A
  #     TTL: 300
  #     ResourceRecords:
  #       - !GetAtt Instance.PrivateIp

  # ReverseRecord:
  #   Type: AWS::Route53::RecordSet
  #   Properties:
  #     HostedZoneId: !ImportValue dns-stack-ReverseZoneId
  #     Name: !Sub
  #       - "${octet3}.${octet2}.${octet1}.${octet0}.in-addr.arpa."
  #       - octet0: !Select [0, !Split [".", !GetAtt Instance.PrivateIp]]
  #         octet1: !Select [1, !Split [".", !GetAtt Instance.PrivateIp]]
  #         octet2: !Select [2, !Split [".", !GetAtt Instance.PrivateIp]]
  #         octet3: !Select [3, !Split [".", !GetAtt Instance.PrivateIp]]
  #     Type: PTR
  #     TTL: 300
  #     ResourceRecords:
  #       - "eks-manager.dev.saber.net"

Outputs:
  SecurityGroupId:
    Description: "ID of OCP Management server security group"
    Value: !Ref SecurityGroup
    Export:
      Name: !Sub "${AWS::StackName}-SecurityGroupId"
