AWSTemplateFormatVersion: '2010-09-09'
Description: Development EKS Manager (management server) stack

# Unlike SSM Session Manager, EC2 Instance Connect requires port
# tcp/22 to be open on the instance's security group.

Parameters:
  AmiId:
    Type: AWS::EC2::Image::Id
    Description: "ID of AMI to use for EKS Manager instance"
    Default: ami-011d5239d6804e25e

Resources:

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Development EKS Manager security group
      VpcId: !ImportValue dev-network-stack-VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          SourceSecurityGroupId: !ImportValue dev-network-stack-ManagementInstanceConnectEndpointSecurityGroupId
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic to anywhere
      Tags:
        - Key: Name
          Value: "dev-eks-manager-sg"

  # The following IAM policy and role are needed to allow the
  # "aws eks update-kubeconfig ..." command to complete successfully.

  ManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: "Allows describing any EKS cluster within this AWS account"
      ManagedPolicyName: dev-eks-manager-policy
      Path: '/'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - "eks:DescribeCluster"
            Resource: !Sub "arn:aws:eks:*:${AWS::AccountId}:cluster/*"

  Role:
    Type: AWS::IAM::Role
    Properties:
      Description: "Development EKS manager role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - !Ref ManagedPolicy
      RoleName: dev-eks-manager-role
      Tags:
        - Key: "Name"
          Value: "dev-eks-manager-role"

  # Our understanding is that since we are creating the role in the
  # same CFn template where the instance is defined, we need to
  # explicity create the IAM profile. Perhaps this requirement can be
  # verified in the future.

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
        - !Ref Role

  # We should use Amazon Linux 2023 AMI. Do not associate a public IP
  # in CFn. Instead, do it manually whenever required to avoid costs
  # associated with a public IP. For instance profile, use a role
  # that has EKS Cluster Admin policy attached.

  # Note: SSM quick setup is probably not required since we are using
  # EC2 Instance Connect instead of SSM Session Manager.

  # Note: Key pair is omitted because we are using EC2 Instance
  # Connect instead of traditional SSH logins.

  Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref AmiId
      InstanceType: t3.micro
      NetworkInterfaces:
        - AssociatePublicIpAddress: false
          DeviceIndex: 0
          GroupSet:
            - !Ref SecurityGroup
          SubnetId: !ImportValue dev-network-stack-ManagementSubnetId
      BlockDeviceMappings:
        - DeviceName: "/dev/xvda"
          Ebs:
            VolumeType: gp3
            DeleteOnTermination: true
            VolumeSize: 10
      IamInstanceProfile: !Ref InstanceProfile
      Tags:
        - Key: Name
          Value: "dev-eks-manager-instance"

  # ForwardRecord:
  #   Type: AWS::Route53::RecordSet
  #   Properties:
  #     HostedZoneId: !ImportValue dns-stack-ForwardZoneId
  #     Name: "eks-manager.dev.saber.net"
  #     Type: A
  #     TTL: 300
  #     ResourceRecords:
  #       - !GetAtt Instance.PrivateIp

  # ReverseRecord:
  #   Type: AWS::Route53::RecordSet
  #   Properties:
  #     HostedZoneId: !ImportValue dns-stack-ReverseZoneId
  #     Name: !Sub
  #       - "${octet3}.${octet2}.${octet1}.${octet0}.in-addr.arpa."
  #       - octet0: !Select [0, !Split [".", !GetAtt Instance.PrivateIp]]
  #         octet1: !Select [1, !Split [".", !GetAtt Instance.PrivateIp]]
  #         octet2: !Select [2, !Split [".", !GetAtt Instance.PrivateIp]]
  #         octet3: !Select [3, !Split [".", !GetAtt Instance.PrivateIp]]
  #     Type: PTR
  #     TTL: 300
  #     ResourceRecords:
  #       - "eks-manager.dev.saber.net"

Outputs:
  SecurityGroupId:
    Description: "ID of EKS Manager security group"
    Value: !Ref SecurityGroup
    Export:
      Name: !Sub "${AWS::StackName}-SecurityGroupId"
