AWSTemplateFormatVersion: "2010-09-09"
Description: Production network advanced stack

Resources:

  # Enables access to S3 from disconnected subnets

  # S3GatewayVPCEndpoint:
  #   Type: AWS::EC2::VPCEndpoint
  #   Properties:
  #     RouteTableIds:
  #       - !ImportValue prod-network-stack-NodeRouteTableId
  #     ServiceName: !Sub "com.amazonaws.${AWS::Region}.s3"
  #     VpcEndpointType: Gateway
  #     VpcId: !ImportValue prod-network-stack-VpcId
  #     Tags:
  #       - Key: Name
  #         Value: prod-s3-gateway-vpce

  # Security group is only used by interface VPC endpoints

  # SecurityGroup:
  #   Type: AWS::EC2::SecurityGroup
  #   Properties:
  #     GroupDescription: Production VPC endpoint security group
  #     VpcId: !ImportValue prod-network-stack-VpcId
  #     SecurityGroupIngress:
  #       - IpProtocol: tcp
  #         FromPort: 443
  #         ToPort: 443
  #         CidrIp: !ImportValue prod-network-stack-VpcCidr
  #     Tags:
  #       - Key: Name
  #         Value: "prod-vpc-endpoint-sg"

  # Enables access to EC2 from disconnected subnets

  # EC2InterfaceVPCEndpoint:
  #   Type: AWS::EC2::VPCEndpoint
  #   Properties:
  #     PrivateDnsEnabled: true
  #     SecurityGroupIds:
  #       - !Ref SecurityGroup
  #     ServiceName: !Sub "com.amazonaws.${AWS::Region}.ec2"
  #     SubnetIds:
  #       - !ImportValue prod-network-stack-NodeSubnet1Id
  #       - !ImportValue prod-network-stack-NodeSubnet2Id
  #       - !ImportValue prod-network-stack-NodeSubnet3Id
  #     VpcEndpointType: Interface
  #     VpcId: !ImportValue prod-network-stack-VpcId
  #     Tags:
  #       - Key: Name
  #         Value: prod-ec2-interface-vpce

  # Enables access to ELB from disconnected subnets

  # ELBInterfaceVPCEndpoint:
  #   Type: AWS::EC2::VPCEndpoint
  #   Properties:
  #     PrivateDnsEnabled: true
  #     SecurityGroupIds:
  #       - !Ref SecurityGroup
  #     ServiceName: !Sub "com.amazonaws.${AWS::Region}.elasticloadbalancing"
  #     SubnetIds:
  #       - !ImportValue prod-network-stack-NodeSubnet1Id
  #       - !ImportValue prod-network-stack-NodeSubnet2Id
  #       - !ImportValue prod-network-stack-NodeSubnet3Id
  #     VpcEndpointType: Interface
  #     VpcId: !ImportValue prod-network-stack-VpcId
  #     Tags:
  #       - Key: Name
  #         Value: prod-elb-interface-vpce

  # Enables access to ECR API from disconnected subnets

  # ECRAPIInterfaceVPCEndpoint:
  #   Type: AWS::EC2::VPCEndpoint
  #   Properties:
  #     PrivateDnsEnabled: true
  #     SecurityGroupIds:
  #       - !Ref SecurityGroup
  #     ServiceName: !Sub "com.amazonaws.${AWS::Region}.ecr.api"
  #     SubnetIds:
  #       - !ImportValue prod-network-stack-NodeSubnet1Id
  #       - !ImportValue prod-network-stack-NodeSubnet2Id
  #       - !ImportValue prod-network-stack-NodeSubnet3Id
  #     VpcEndpointType: Interface
  #     VpcId: !ImportValue prod-network-stack-VpcId
  #     Tags:
  #       - Key: Name
  #         Value: prod-ecr-api-interface-vpce

  # Enables access to ECR Docker from disconnected subnets

  # ECRDockerInterfaceVPCEndpoint:
  #   Type: AWS::EC2::VPCEndpoint
  #   Properties:
  #     PrivateDnsEnabled: true
  #     SecurityGroupIds:
  #       - !Ref SecurityGroup
  #     ServiceName: !Sub "com.amazonaws.${AWS::Region}.ecr.dkr"
  #     SubnetIds:
  #       - !ImportValue prod-network-stack-NodeSubnet1Id
  #       - !ImportValue prod-network-stack-NodeSubnet2Id
  #       - !ImportValue prod-network-stack-NodeSubnet3Id
  #     VpcEndpointType: Interface
  #     VpcId: !ImportValue prod-network-stack-VpcId
  #     Tags:
  #       - Key: Name
  #         Value: prod-ecr-docker-interface-vpce

  # Enables access to STS from disconnected subnets

  # STSInterfaceVPCEndpoint:
  #   Type: AWS::EC2::VPCEndpoint
  #   Properties:
  #     PrivateDnsEnabled: true
  #     SecurityGroupIds:
  #       - !Ref SecurityGroup
  #     ServiceName: !Sub "com.amazonaws.${AWS::Region}.sts"
  #     SubnetIds:
  #       - !ImportValue prod-network-stack-NodeSubnet1Id
  #       - !ImportValue prod-network-stack-NodeSubnet2Id
  #       - !ImportValue prod-network-stack-NodeSubnet3Id
  #     VpcEndpointType: Interface
  #     VpcId: !ImportValue prod-network-stack-VpcId
  #     Tags:
  #       - Key: Name
  #         Value: prod-sts-interface-vpce

  # NAT is an alternative to using VPC endpoints.

  NATEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  NATGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NATEIP.AllocationId
      SubnetId: !ImportValue prod-network-stack-PublicSubnetId
      Tags:
        - Key: Name
          Value: prod-nat-gateway

  NodeSubnetRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !ImportValue prod-network-stack-NodeRouteTableId
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NATGateway
