AWSTemplateFormatVersion: '2010-09-09'
Description: Development EKS cluster stack

Resources:

  EKSClusterRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "eks.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Description: EKS cluster role
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonEKSClusterPolicy"
      RoleName: dev-eks-cluster-role
      Tags:
        - Key: "Name"
          Value: "dev-eks-cluster-role"

  # An additional security group beyond the one that is automatically
  # created by AWS during EKS cluster creation. The purpose of this
  # additional security group is to allow access from the EKS manager
  # instance.

  EKSClusterAccessSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: EKS cluster access security group
      VpcId: !ImportValue dev-network-stack-VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          SourceSecurityGroupId: !ImportValue dev-eks-manager-stack-SecurityGroupId
          Description: Allow inbound HTTP
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic to anywhere
      Tags:
        - Key: Name
          Value: "dev-eks-cluster-access-sg"

  # I believe we can disable bootstrapping the cluster creator admin
  # permissions because we plan to use an EKS management server that
  # has a role attached that allows cluster administration. But for
  # now just leave it as true, which is the default setting.

  # Note: We want to disable bootstrapping of self-managed add-ons
  # and add them explicitly instead. This gives more control and
  # insight over the core add-ons.

  EKSCluster:
      Type: AWS::EKS::Cluster
      Properties:
        Name: Dev
        Version: "1.36"
        AccessConfig:
          AuthenticationMode: API
          BootstrapClusterCreatorAdminPermissions: true
        BootstrapSelfManagedAddons: false
        RoleArn: !GetAtt EKSClusterRole.Arn
        ResourcesVpcConfig:
          SecurityGroupIds:
            - !Ref EKSClusterAccessSecurityGroup
          SubnetIds:
            - !ImportValue dev-network-stack-NodeSubnet1Id
            - !ImportValue dev-network-stack-NodeSubnet2Id
            - !ImportValue dev-network-stack-NodeSubnet3Id
          EndpointPrivateAccess: true
          EndpointPublicAccess: false
        Tags:
          - Key: "Creator"
            Value: "maxwell"

  # To set up a basic EKS cluster, these add-ons are more-or-less
  # required.

  VPCCNIAddon:
    Type: AWS::EKS::Addon
    Properties:
      AddonName: vpc-cni
      ClusterName: !Ref EKSCluster
      ResolveConflicts: OVERWRITE

  CoreDNSAddon:
    Type: AWS::EKS::Addon
    Properties:
      AddonName: coredns
      ClusterName: !Ref EKSCluster
      ResolveConflicts: OVERWRITE

  KubeProxyAddon:
    Type: AWS::EKS::Addon
    Properties:
      AddonName: kube-proxy
      ClusterName: !Ref EKSCluster
      ResolveConflicts: OVERWRITE

  EKSPodIdentityAgentAddon:
    Type: AWS::EKS::Addon
    Properties:
      AddonName: eks-pod-identity-agent
      ClusterName: !Ref EKSCluster
      ResolveConflicts: OVERWRITE

  # This access entry gives the EKS manager (management server)
  # cluster admin permissions.

  AccessEntry:
    Type: AWS::EKS::AccessEntry
    Properties:
      AccessPolicies:
        - PolicyArn: "arn:aws:eks::aws:cluster-access-policy/AmazonEKSClusterAdminPolicy"
          AccessScope:
            Type: cluster
      ClusterName: Dev
      PrincipalArn: !Sub "arn:aws:iam::${AWS::AccountId}:role/dev-eks-manager-role"
      Type: STANDARD

  # This role is created here in preparation for creating one or more
  # node groups. We need to use kubectl to associate it with a
  # service account before the node group(s) are created.

  EKSVPCCNIRole:
    Type: AWS::IAM::Role
    Properties:
      Description: EKS VPC CNI role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "pods.eks.amazonaws.com"
            Action:
              - "sts:AssumeRole"
              - "sts:TagSession"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy"
      RoleName: dev-eks-vpc-cni-role
      Tags:
        - Key: "Name"
          Value: "dev-eks-vpc-cni-role"

  EKSVPCCNIPodIdentityAssociation:
    Type: AWS::EKS::PodIdentityAssociation
    Properties:
      ClusterName: Dev
      Namespace: kube-system
      RoleArn: !Sub "arn:aws:iam::${AWS::AccountId}:role/dev-eks-vpc-cni-role"
      ServiceAccount: aws-node
