AWSTemplateFormatVersion: '2010-09-09'
Description: Development EKS node group stack

Resources:

  # Does this require an IAM profile?

  EKSNodeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Description: EKS node role
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy"
        - "arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryPullOnly"
      RoleName: dev-eks-node-role
      Tags:
        - Key: "Name"
          Value: "dev-eks-node-role"
        - Key: "Force"
          Value: 0

  # Not sure if this is needed or not. Added for troubleshooting
  # problem with node group not getting past creating status.

  EKSNodeInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
        - !Ref EKSNodeRole

  # Need NAT gateways for this to work.

  EKSNodegroup:
    Type: AWS::EKS::Nodegroup
    Properties:
      AmiType: AL2023_x86_64_STANDARD
      ClusterName: Dev
      InstanceTypes:
        - t3.medium
      NodegroupName: basic
      NodeRole: !Sub "arn:aws:iam::${AWS::AccountId}:role/dev-eks-node-role"
      ScalingConfig:
        MinSize: 0
        DesiredSize: 2
        MaxSize: 2
      Subnets:
        - !ImportValue dev-network-stack-NodeSubnet1Id
        - !ImportValue dev-network-stack-NodeSubnet2Id
        - !ImportValue dev-network-stack-NodeSubnet3Id
