AWSTemplateFormatVersion: '2010-09-09'
Description: Development EKS cluster stack

Resources:

  EKSClusterRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "eks.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Description: EKS cluster role
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonEKSClusterPolicy"
      RoleName: dev-eks-cluster-role
      Tags:
        - Key: "Name"
          Value: "dev-eks-cluster-role"

  # An additional security group beyond the one that is automatically
  # created by AWS during EKS cluster creation. The purpose of this
  # additional security group is to allow access from the EKS manager
  # instance.

  EKSClusterAccessSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: EKS cluster access security group
      VpcId: !ImportValue dev-network-stack-VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          SourceSecurityGroupId: !ImportValue dev-eks-manager-stack-SecurityGroupId
          Description: Allow inbound HTTP
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic to anywhere
      Tags:
        - Key: Name
          Value: "dev-eks-cluster-access-sg"

  EKSCluster:
      Type: AWS::EKS::Cluster
      Properties:
        Name: Dev
        Version: "1.36"
        AccessConfig:
          AuthenticationMode: API
          BootstrapClusterCreatorAdminPermissions: true
        BootstrapSelfManagedAddons: false
        RoleArn: !GetAtt EKSClusterRole.Arn
        ResourcesVpcConfig:
          SecurityGroupIds:
            - !Ref EKSClusterAccessSecurityGroup
          SubnetIds:
            - !ImportValue dev-network-stack-NodeSubnet1Id
            - !ImportValue dev-network-stack-NodeSubnet2Id
            - !ImportValue dev-network-stack-NodeSubnet3Id
          EndpointPrivateAccess: true
          EndpointPublicAccess: false
        Tags:
          - Key: "Creator"
            Value: "maxwell"

  # To set up a basic EKS cluster, these add-ons are more-or-less
  # required.

  VPCCNIAddon:
    Type: AWS::EKS::Addon
    Properties:
      AddonName: vpc-cni
      ClusterName: !Ref EKSCluster
      ResolveConflicts: OVERWRITE

  CoreDNSAddon:
    Type: AWS::EKS::Addon
    Properties:
      AddonName: coredns
      ClusterName: !Ref EKSCluster
      ResolveConflicts: OVERWRITE

  KubeProxyAddon:
    Type: AWS::EKS::Addon
    Properties:
      AddonName: kube-proxy
      ClusterName: !Ref EKSCluster
      ResolveConflicts: OVERWRITE

  # This access entry gives the EKS manager (management server)
  # cluster admin permissions.

  AccessEntry:
    Type: AWS::EKS::AccessEntry
    Properties:
      AccessPolicies:
        - PolicyArn: "arn:aws:eks::aws:cluster-access-policy/AmazonEKSClusterAdminPolicy"
          AccessScope:
            Type: cluster
      ClusterName: Dev
      PrincipalArn: "arn:aws:iam::164599051561:role/dev-eks-manager-role"
      Type: STANDARD
