AWSTemplateFormatVersion: '2010-09-09'
Description: Development EKS Manager (management server) stack

# Unlike SSM Session Manager, EC2 Instance Connect requires port
# tcp/22 to be open on the instance's security group.

Parameters:
  AmiId:
    Type: AWS::EC2::Image::Id
    Description: "ID of AMI to use for EKS Manager instance"
    Default: ami-011d5239d6804e25e

Resources:

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Development EKS Manager security group
      VpcId: !ImportValue dev-network-stack-VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          SourceSecurityGroupId: !ImportValue dev-network-stack-ManagementInstanceConnectEndpointSecurityGroupId
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic to anywhere
      Tags:
        - Key: Name
          Value: "dev-eks-manager-sg"

  # I believe this role needs to allow it to be an EKS cluster
  # administrator. But I can't find that policy anywhere. I thought
  # I saw it before, so will need to look for it again.

  # EKSManagerRole:
  #   Type: AWS::IAM::Role
  #   Properties:
  #     AssumeRolePolicyDocument:
  #       Version: "2012-10-17"
  #       Statement:
  #         - Effect: "Allow"
  #           Principal:
  #             Service:
  #               - "eks.amazonaws.com"
  #           Action:
  #             - "sts:AssumeRole"
  #     Description: EKS manager role
  #     ManagedPolicyArns:
  #       - "arn:aws:iam::aws:policy/AmazonEKSClusterPolicy"
  #     RoleName: eksClusterRole
  #     Tags:
  #       - Key: "Name"
  #         Value: "eks_cluster_role"

  # We should use Amazon Linux 2023 AMI. Do not associate a public IP
  # in CFn. Instead, do it manually whenever required to avoid costs
  # associated with a public IP. For instance profile, use a role
  # that has EKS Cluster Admin policy attached.

  # Note: SSM quick setup is probably not required since we are using
  # EC2 Instance Connect instead of SSM Session Manager.

  # Note: Key pair is omitted because we are using EC2 Instance
  # Connect instead of traditional SSH logins.

  Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref AmiId
      InstanceType: t3.micro
      NetworkInterfaces:
        - AssociatePublicIpAddress: false
          DeviceIndex: 0
          GroupSet:
            - !Ref SecurityGroup
          SubnetId: !ImportValue dev-network-stack-ManagementSubnetId
      BlockDeviceMappings:
        - DeviceName: "/dev/xvda"
          Ebs:
            VolumeType: gp3
            DeleteOnTermination: true
            VolumeSize: 10
      IamInstanceProfile: ssm-quick-setup
      Tags:
        - Key: Name
          Value: "dev-eks-manager-instance"

  # ForwardRecord:
  #   Type: AWS::Route53::RecordSet
  #   Properties:
  #     HostedZoneId: !ImportValue dns-stack-ForwardZoneId
  #     Name: "eks-manager.dev.saber.net"
  #     Type: A
  #     TTL: 300
  #     ResourceRecords:
  #       - !GetAtt Instance.PrivateIp

  # ReverseRecord:
  #   Type: AWS::Route53::RecordSet
  #   Properties:
  #     HostedZoneId: !ImportValue dns-stack-ReverseZoneId
  #     Name: !Sub
  #       - "${octet3}.${octet2}.${octet1}.${octet0}.in-addr.arpa."
  #       - octet0: !Select [0, !Split [".", !GetAtt Instance.PrivateIp]]
  #         octet1: !Select [1, !Split [".", !GetAtt Instance.PrivateIp]]
  #         octet2: !Select [2, !Split [".", !GetAtt Instance.PrivateIp]]
  #         octet3: !Select [3, !Split [".", !GetAtt Instance.PrivateIp]]
  #     Type: PTR
  #     TTL: 300
  #     ResourceRecords:
  #       - "eks-manager.dev.saber.net"

Outputs:
  SecurityGroupId:
    Description: "ID of EKS Manager security group"
    Value: !Ref SecurityGroup
    Export:
      Name: !Sub "${AWS::StackName}-SecurityGroupId"
