AWSTemplateFormatVersion: '2010-09-09'
Description: Shared services stack

Parameters:
  VpcCidr:
    Type: String
    Description: "CIDR block of VPC"
    Default: 10.0.2.0/24
  IngressSubnet1Cidr:
    Type: String
    Description: "CIDR block of ingress subnet in AZ A"
    Default: 10.0.2.0/27
  IngressSubnet2Cidr:
    Type: String
    Description: "CIDR block of ingress subnet in AZ B"
    Default: 10.0.2.32/27
  AppSubnet1Cidr:
    Type: String
    Description: "CIDR block of app subnet in AZ A"
    Default: 10.0.2.64/27
  AppSubnet2Cidr:
    Type: String
    Description: "CIDR block of app subnet in AZ B"
    Default: 10.0.2.96/27
  DataSubnet1Cidr:
    Type: String
    Description: "CIDR block of data subnet in AZ A"
    Default: 10.0.2.128/27
  DataSubnet2Cidr:
    Type: String
    Description: "CIDR block of data subnet in AZ B"
    Default: 10.0.2.160/27
  TgwSubnet1Cidr:
    Type: String
    Description: "CIDR block of TGW subnet in AZ A"
    Default: 10.0.2.224/28
  TgwSubnet2Cidr:
    Type: String
    Description: "CIDR block of TGW subnet in AZ B"
    Default: 10.0.2.240/28

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: "shared-services-vpc"

  IngressSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Sub "${AWS::Region}a"
      CidrBlock: !Ref IngressSubnet1Cidr
      MapPublicIpOnLaunch: false
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: "shared-services-ingress-subnet-a"

  IngressSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Sub "${AWS::Region}b"
      CidrBlock: !Ref IngressSubnet2Cidr
      MapPublicIpOnLaunch: false
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: "shared-services-ingress-subnet-b"

  AppSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Sub "${AWS::Region}a"
      CidrBlock: !Ref AppSubnet1Cidr
      MapPublicIpOnLaunch: false
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: "shared-services-app-subnet-a"

  AppSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Sub "${AWS::Region}b"
      CidrBlock: !Ref AppSubnet2Cidr
      MapPublicIpOnLaunch: false
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: "shared-services-app-subnet-b"

  DataSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Sub "${AWS::Region}a"
      CidrBlock: !Ref DataSubnet1Cidr
      MapPublicIpOnLaunch: false
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: "shared-services-data-subnet-a"

  DataSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Sub "${AWS::Region}b"
      CidrBlock: !Ref DataSubnet2Cidr
      MapPublicIpOnLaunch: false
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: "shared-services-data-subnet-b"

  TgwSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Sub "${AWS::Region}a"
      CidrBlock: !Ref TgwSubnet1Cidr
      MapPublicIpOnLaunch: false
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: "shared-services-tgw-subnet-a"

  TgwSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Sub "${AWS::Region}b"
      CidrBlock: !Ref TgwSubnet2Cidr
      MapPublicIpOnLaunch: false
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: "shared-services-tgw-subnet-b"

  # Create custom route tables and explicitly associate subnets to
  # override the default route table.

  IngressRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: "shared-services-ingress-rtb"

  # Even though the app subnet is private, it may have a NAT gateway that
  # allows it to reach the internet.

  AppRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: "shared-services-private-rtb"

  # The data subnet may not have a NAT gateway if only contains managed
  # databases.

  DataRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: "shared-services-private-rtb"

  TgwRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: "shared-services-tgw-rtb"

  IngressSubnet1Association:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref IngressSubnet1
      RouteTableId: !Ref IngressRouteTable

  IngressSubnet2Association:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref IngressSubnet2
      RouteTableId: !Ref IngressRouteTable

  AppSubnet1Association:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref AppSubnet1
      RouteTableId: !Ref AppRouteTable

  AppSubnet2Association:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref AppSubnet2
      RouteTableId: !Ref AppRouteTable

  DataSubnet1Association:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref DataSubnet1
      RouteTableId: !Ref DataRouteTable

  DataSubnet2Association:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref DataSubnet2
      RouteTableId: !Ref DataRouteTable

  TgwSubnet1Association:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref TgwSubnet1
      RouteTableId: !Ref TgwRouteTable

  TgwSubnet2Association:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref TgwSubnet2
      RouteTableId: !Ref TgwRouteTable

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: "shared-services-igw"

  GatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  IngressRoute:
    Type: AWS::EC2::Route
    DependsOn: GatewayAttachment
    Properties:
      RouteTableId: !Ref IngressRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

Outputs:
  VpcId:
    Description: "The ID of the VPC"
    Value: !Ref VPC
    Export:
      Name: !Sub "${AWS::StackName}-VpcId"
  IngressSubnet1Id:
    Description: "The ID of the ingress subnet in AZ A"
    Value: !Ref IngressSubnet1
    Export:
      Name: !Sub "${AWS::StackName}-IngressSubnet1Id"
  IngressSubnet2Id:
    Description: "The ID of the ingress subnet in AZ B"
    Value: !Ref IngressSubnet2
    Export:
      Name: !Sub "${AWS::StackName}-IngressSubnet2Id"
  AppSubnet1Id:
    Description: "The ID of the app subnet in AZ A"
    Value: !Ref AppSubnet1
    Export:
      Name: !Sub "${AWS::StackName}-AppSubnet1Id"
  AppSubnet2Id:
    Description: "The ID of the app subnet in AZ B"
    Value: !Ref AppSubnet2
    Export:
      Name: !Sub "${AWS::StackName}-AppSubnet2Id"
  DataSubnet1Id:
    Description: "The ID of the data subnet in AZ A"
    Value: !Ref DataSubnet1
    Export:
      Name: !Sub "${AWS::StackName}-DataSubnet1Id"
  DataSubnet2Id:
    Description: "The ID of the data subnet in AZ B"
    Value: !Ref DataSubnet2
    Export:
      Name: !Sub "${AWS::StackName}-DataSubnet2Id"
  TgwSubnet1Cidr:
    Description: "CIDR block of TGW subnet in AZ A"
    Value: !Ref TgwSubnet1Cidr
    Export:
      Name: !Sub "${AWS::StackName}-TgwSubnet1Cidr"
  TgwSubnet2Cidr:
    Description: "CIDR block of TGW subnet in AZ B"
    Value: !Ref TgwSubnet2Cidr
    Export:
      Name: !Sub "${AWS::StackName}-TgwSubnet2Cidr"

