AWSTemplateFormatVersion: '2010-09-09'
Description: Shared services ECS stack

Resources:

  ECSServiceLinkedRole:
    Type: AWS::IAM::ServiceLinkedRole
    Properties:
      AWSServiceName: ecs.amazonaws.com
      Description: ECS service-linked role

  ECSCluster:
    Type: AWS::ECS::Cluster
    DependsOn: ECSServiceLinkedRole
    Properties:
      ClusterName: shared-services-ecs-cluster

  # This task execution role is normally needed so that the ECS agent can
  # perform its required actions such as pulling container images from ECR or
  # sending logs to CloudWatch Logs. In some cases, additional permissions are
  # required (e.g. to access Secrets Manager).

  ECSTaskExecutionRole:
    Type: AWS::IAM::Role
    DependsOn: ECSServiceLinkedRole
    Properties:
      RoleName: ecs-task-execution-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
