AWSTemplateFormatVersion: '2010-09-09'
Description: VPC peering stack

Resources:
  VpcPeeringConnection:
    Type: AWS::EC2::VPCPeeringConnection
    Properties:
      VpcId: !ImportValue inspection-stack-VpcId
      PeerVpcId: !ImportValue shared-services-stack-VpcId
      Tags:
      - Key: Name
        Value: inspection-and-shared-services-pcx

